version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  create-file1:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Create file1
          command: |
            mkdir -p workspace
            echo "1111111" > workspace/file1-<< pipeline.number >>
            ls workspace/
            cat workspace/file1-<< pipeline.number >>
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'

  create-file2:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Create file2
          command: |
            mkdir -p workspace
            echo "222222" > workspace/file2-<< pipeline.number >>
            ls workspace/
            cat workspace/file2-<< pipeline.number >>
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'

  create-file3:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Create file3
          command: |
            mkdir -p workspace
            echo "333333" > workspace/file3-<< pipeline.number >>
            ls workspace/
            cat workspace/file3-<< pipeline.number >>
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'

  update-file:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy and update file1 to file2
          command: |
            cp /tmp/workspace/file*-<< pipeline.number >> /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - '*'

  list-files:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: List files in workspace
          command: |
            ls
            ls /tmp/workspace
            cat *


workflows:
  version: 2
  build:
    jobs:
      - create-file1
      - create-file2
      - create-file3
      - update-file:
          requires:
            - create-file1
            - create-file2
            - create-file3
      - list-files:
          requires:
            - update-file
