version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  create-file:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Create file1
          command: |
            mkdir workspace
            echo "1111111" > workspace/file1
      - persist_to_workspace:
          root: workspace
          paths:
            - file1

  update-file:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy and update file1 to file2
          command: |
            cp /tmp/workspace/file1 /tmp/workspace/file2
            echo "2222222" > workspace/file2
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - file2

  list-files:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: List files in workspace
          command: ls /tmp/workspace


workflows:
  version: 2
  build:
    jobs:
      - create-file
      - update-file:
          requires:
            - create-file
      - list-files:
          requires:
            - update-file
