# This file demonstrates how to leverage Setup Workflows to generate dynamic config files using scripts.

version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run: 
          name: Generate Pipeline generated_config.yml file
          command: |
            ./.circleci/generate-pipeline-config
      - continuation/continue:
          parameters: '{}'
          configuration_path: .circleci/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config
