version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  create-file:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Create file1
          command: |
            mkdir -p workspace
            echo "1111111" > workspace/file1-<< pipeline.id >>
            ls workspace/
            cat workspace/file1-<< pipeline.id >>
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'

  update-file:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy and update file1 to file2
          command: |
            cp /tmp/workspace/file1-<< pipeline.id >> /tmp/workspace/file2-<< pipeline.id >>
            echo "2222222" > /tmp/workspace/file2-<< pipeline.id >>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - '*'

  list-files:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: List files in workspace
          command: ls && ls /tmp/workspace && cat *


workflows:
  version: 2
  build:
    jobs:
      - create-file
      - update-file:
          requires:
            - create-file
      - list-files:
          requires:
            - update-file
