version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  create-file:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Create file1
          command: |
            mkdir workspace
            echo "1111111" > workspace/file1
      - persist_to_workspace:
          root: workspace
          paths:
            - file1

workflows:
  version: 2
  build:
    jobs:
      - create-file
