#!/bin/bash 
set -o pipefail

#TF_VERSION=$1 #Terraform CLI Version to install
#DOCTL_VERSION=$2 #Digital Ocean CLI Version to install

mkdir configs/
cat << EOF > .circleci/generated_config.yml
version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/python:3.8

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: workspace
      paths:
        - '*'

commands: 
  add-file:
      description: add file with params
      parameters:
        file_name:
          type: string
        text:
          type: string
      steps:
        - checkout
        - run:
            name: Create file
            command: |
              mkdir -p workspace
              echo "<< parameters.text >>" > workspace/<< parameters.file_name >>-<< pipeline.number >>
              ls workspace/
              cat workspace/<< parameters.file_name >>-<< pipeline.number >>
        - *persist_to_workspace

jobs:
  create-file1:
    executor: default-executor
    steps:
      - add-file:
          file_name: f1
          text: t1

  create-file2:
    executor: default-executor
    steps:
      - add-file:
          file_name: f2
          text: t2

  create-file3:
    executor: default-executor
    steps:
      - add-file:
          file_name: f3
          text: t3

  update-file:
    executor: default-executor
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: update
          command: |
            ls /tmp/workspace/
            echo "~~~~"
            for file in /tmp/workspace/*; do
                echo "file name: ~\$file~"
                echo "oooooooooo" >> "\$file"
            done
            echo "~~~~"
      - *persist_to_workspace

  list-files:
    executor: default-executor
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: List files in workspace
          command: |
            ls
            ls /tmp/workspace
            cat /tmp/workspace/*


workflows:
  version: 2
  build:
    jobs:
      - create-file1
      - create-file2
      - create-file3
      - update-file:
          requires:
            - create-file1
            - create-file2
            - create-file3
      - list-files:
          requires:
            - update-file
EOF
