name: PR e2e
on: [push]

jobs:

  e2e-terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Terraform repo
        uses: actions/checkout@v2     
      - name: Terraform workspace - apply with sha and branch
        env:
          var: megavar
        id: output_env
        run: |
           chmod +x .github/workflows/dir/script.sh
           bash -eux .github/workflows/dir/script.sh
          
