name: PR e2e
on: [push]

jobs:

  e2e-terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Terraform repo
        uses: actions/checkout@v2     
      - name: Terraform workspace - apply with sha and branch
        id: output_env
        run: |
          is_snyk=$(echo "[Snyk]" | grep -eo \[Snyk\] )
          if [ ! -z "$is_snyk" ]; then
             echo "This PR iscreated by Snyk"
             exit 0
          fi
