name: PR e2e
on: [push]

jobs:
  build-push-deploy-validate:
    strategy:
      matrix:
        include:
          - branch: refs/heads/master
          - branch: refs/heads/master

    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        if: ${{ github.ref == matrix.branch }}
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Task Vaildation
        id: validator
        shell: bash
        env:
           cluster: ${{ matrix.cluster }}
           service: ${{ matrix.service }}
           should_descale: ${{ matrix.should_descale }}
        run: |
           chmod +x .github/workflows/dir/script.sh
           .github/workflows/dir/script.sh

      - name: Slack Notification - suceeded
        if: ${{ 'refs/heads/master' == matrix.branch }} && steps.validator.outcome == 'success'
        run: |
          echo "good"

      - name: Slack Notification - failed
        if: ${{ 'refs/heads/master' == matrix.branch }} && failure() && steps.validator.outcome == 'failure'
        run: |
          echo "bad"     
